version: '3'

services:
  aws-dropbox:
    build: .
    image: aws-dropbox
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/aws-dropbox
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/aws-dropbox
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
